// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  h2_header: dynamic(() => import("./H2Header")),
  header: dynamic(() => import("./Header")),
  image: dynamic(() => import("./Image")),
  quote: dynamic(() => import("./Quote")),
  table: dynamic(() => import("./Table")),
  text: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
};
